config/routes.rb
Rails.application.routes.draw do
  get 'users/list'
  get 'users/new'
  get 'users/delete'
  post 'users/create'
  get 'users/confirm'
  post 'users/confirm'
  get 'users/showProfile'
  get 'users/editProfile'
  post 'users/search'
  get 'posts/list'
  get 'posts/new'
  get 'posts/upload'
  get 'posts/export'
  post 'posts/create'
  get 'posts/edit'
  post 'posts/update'
  get 'posts/confirm'
  post 'posts/confirm'
  get 'posts/delete'
  post 'posts/import'
  post 'posts/search'
  root 'auths#login'
  get 'auths/login'
  get 'auths/logout'
  post 'auths/authenticate'
  get 'auths/changePsw'
  post 'auths/updatePsw'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
  resources :posts

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :description, presence: true, uniqueness:true
  
    def self.import(file)
      csv = CSV.parse(file, :headers => true)
       csv.each do |row|
        Moulding.create!(row.to_hash)
      end
    end

    def self.to_excel(options={})
      CSV.generate(options) do |csv|
        csv << column_names
        all.each do |post|
          csv  << post.attributes.values_at(*column_names)
        end
      end
    end

    
end

app/models/user.rb
class User < ApplicationRecord
    VALID_EMAIL_REGEX = /\A[\w+\-]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true,
              uniqueness: { case_sensitive: false },
              format: { with: VALID_EMAIL_REGEX}         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
protected
before_action :authorize
def authorize
    unless User.find_by(id: session[:user_id])
        redirect_to root_path, notice:"You trying to unauthorize access."
    end
end

end

app/controllers/auths_controller.rb
class AuthsController < ApplicationController
    skip_before_action :authorize, only: [:login, :authenticate, :logout]
    def login
    end

    def authenticate
        @user = User.find_by(email: params[:email])

        if @user && @user.password == params[:password]
            session[:user_id] = @user.id
            session[:user_name] = @user.name
            if @user.user_type == 0
                session[:user_type] = 'Admin'
            else
                session[:user_type] = 'User'
            end
            session[:user_email] = @user.email
            session[:user_phone] = @user.phone
            session[:user_dob] = @user.dob
            session[:user_address] = @user.address
            redirect_to posts_list_path
        else
            redirect_to request.referer, notice: "Something went wrong! Please Check your email or password."
        end
    end

    def logout
        session[:user_id] = nil
        session[:user_name] = 'Username'
        render :login
    end

    def updatePsw
        @user = User.find(session[:user_id])
        password = params[:password]
        newPassword = params[:newPassword]
        confirmPassword = params[:confirmPassword]
        if password == @user.password
            if  newPassword == confirmPassword
                @user.password = confirmPassword
                @user.save
                redirect_to :action => 'list', :controller=> 'posts'
            else
                redirect_to auths_changePsw_path , notice: "New password and confirm password must be same."
            end
        else
            redirect_to auths_changePsw_path, notice: "Please enter your old password."
        end
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authorize, only: [:create]

  def new
    @post = PostsService.newPost
  end
  
  def confirm
    @post = PostsService.confirmPost(post_params)
    render 'confirmPost'
  end

  def create
    id = session[:user_id]
    isSavePost = PostsService.createPost(post_params, id)
    if isSavePost == nil
      redirect_to posts_new_path, notice: "Title cannot be duplicated."
    else
      redirect_to action: :list
    end
  end

  def show
    @post = PostsService.showPost(params[:id])
    render 'showDetail'
  end

  def list
    @posts = PostsService.listAll.paginate(page: params[:page], per_page:7)
  end

  def edit
    @post = PostsService.editPost(params[:id])
  end

  def update
    user_id = session[:user_id]
    isUpdatePost = PostsService.updatePost(params[:id], post_params, user_id)
    if isUpdatePost
      redirect_to posts_list_path
    else
      redirect_to posts_edit_path
    end
  end

  def delete
    PostsService.deletePost(params[:id])
    redirect_to :action => 'list'
  end

  def profile
  end

  def upload
  end
  
  def search
    @posts = PostsService.searchPost(params[:search]).paginate(page: params[:page], per_page:7)
      render 'list'
  end

  def import
    Post.import(params[:file])
    redirect_to :action => 'list'
  end

  def export
    respond_to do |format|
      format.html
      format.xls {send_data Post.to_excel(col_sep: "\t") }
    end
end

  private

  def post_params
    params.require(:post).permit( :title, :description, :status, :create_user_id, :updated_user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorize, only: [:create]
  
  def list
    @users = UsersService.listAll.paginate(page: params[:page], per_page:6)
  end

  def confirm
    @user = User.new(user_params)
    render 'confirmUser'
  end

  def create
    id = session[:user_id]
    isSaveUser = UsersService.createUser(user_params, id)
      if isSaveUser
        redirect_to action: :list
      else
        redirect_to users_new_path
      end
  end

  def delete
    UsersService.deleteUser(params[:id])
    redirect_to :action => 'list'
  end

  def showProfile
    id = session[:user_id]
    @user = UsersService.showProfile(id)
    render 'profile'
  end

  def editProfile
    @user = UsersService.editProfile(params[:id])
  end

  def update
    user_id = session[:user_id]
    isUpdateProfile = UsersService.updateProfile(params[:id], user_params, user_id)
    if isUpdateProfile 
      redirect_to :action => 'list'
    else
      render 'editProfile'
    end
  end

  def search
    @users = UsersService.searchUser(params[:name], params[:email], params[:from_date], params[:to_date]).paginate(page: params[:page], per_page:6)
    render 'list'
  end

  private

  def user_params
    params.require(:user).permit( :name, :email, :password, :user_type, :phone, :dob, :address, :profile)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auths_helper.rb
module AuthsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/auths/changePsw.html.erb
<h3>Change Password</h3><br>
<p><%= notice %></p>
<%= form_tag :action => 'updatePsw' do %>
<div class="container">
<div class="form-group">
 <label>Current Password:</label>
 <%= password_field_tag :password, params[:password], class:'form-control' %>
</div>
<div class="form-group">
<label>New Password:</label>
<%= password_field_tag :newPassword, params[:newPassword], class:'form-control' %>
</div>
<div class="form-group">
<label>Confirm New Password:</label>
<%= password_field_tag :confirmPassword, params[:confirmPassword], class:'form-control' %>
</div>
<br>
<%= submit_tag 'Update Password', class:'btn btn-info' %>
</div>
<% end %>

app/views/auths/login.html.erb
<div class="container"> 
<h2>Log In</h2><br>
<%= form_tag :action => 'authenticate' do %>
<div class="form-group">
<label>Email:</label><br>
<%= text_field_tag :email, params[:email] , class:'form-control' %>
</div>
<div class="form-group">
<label>Password:</label><br/>
<%= password_field_tag :password, params[:password] , class:'form-control' %>
</div><br>
<div class="form-group">
<%= check_box_tag :remember%>
<label>Remember Me</label>
</div><br>
<%= submit_tag "Login", class:'btn btn-primary' %>
<%= link_to 'Forgot Your Password' %>
<% end -%><br>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg" style="background-color:#00dbdb;">
  <div class="container-fluid">
  <%= link_to 'BulletinBoard', posts_list_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to 'Users', users_list_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
        <%= link_to 'Posts', posts_list_path, class:"nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav navbar-right">
      <li class="nav-item">
      <%= link_to 'Create User', users_new_path, class:"nav-link active" %>
        </li>
      <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        <%= session[:user_name] %>
      </a>
      <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
        <li> <%= link_to 'Profile', users_showProfile_path, class:"dropdown-item" %></li>
        <% if session[:user_id] != nil %>
        <li> <%= link_to 'LogOut', auths_logout_path, class:"dropdown-item" %></li>
        <% else %>
        <li> <%= link_to 'LogIn', auths_login_path, class:"dropdown-item" %></li>
        <% end %>
      </ul>
    </li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application'%>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'%>
</head>
    <title>BulletinBoard</title>
</head>
  <body>
  <%= render 'home/header' %>
  <div class="container-fluid">
  <% if !flash[:notice].blank? %>
   <div class = "alert alert-danger">
      <%= flash[:notice] %>
   </div>
  <% end %>
  <%= yield %>
    
  </div>  
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/posts/confirmPost.html.erb
<% if @post.errors.any? %>
<ul>
<% @post.errors.full_messages.each do |msg| %>
<li><%= msg %>
<% end %>
</ul>
<% end %>
<div class="container">
<h3>Confirm Post</h3><br>
<%= form_for @post, :url =>{:action => "create"}  do %>
<div class="form-group">
<label for = "post_title">Title:</label><br>
<%= text_field 'post', 'title' , class:'form-control' %>
</div><br>
<div class="form-group">
<label for = "post_description">Description:</label><br/>
<%= text_area 'post', 'description' , class:'form-control' %>
</div>
<br>
<%= hidden_field 'post', 'create_user_id'  %>
<%= hidden_field 'post', 'updated_user_id'  %>
<%= submit_tag "Confirm", class:'btn btn-primary' %>
<input type="reset" class="btn btn-secondary" name="Clear" value="Clear">
<% end -%><br>
<%= link_to 'Back', {:action => 'list'} %>
</div>

app/views/posts/edit.html.erb
<% if @post.errors.any? %>
<ul>
<% @post.errors.full_messages.each do |msg| %>
<li><%= msg %>
<% end %>
</ul>
<% end %>
<div class="container">
<h3>Post edit</h3><br>
<%= form_for @post, :url =>{:action => "update", :id => @post.id} do %>
<div class="form-group">
<label for = "post_title">Title:</label><br>
<%= text_field 'post', 'title' , class:'form-control' %>
</div><br>
<div class="form-group">
<label for = "post_description">Description:</label><br/>
<%= text_area 'post', 'description' , class:'form-control' %>
</div>
<br>
<div class="form-group">
<label for = "post_status">Status:</label>
<%= check_box 'post', 'status'  %>
</div><br>
<%= hidden_field 'post', 'create_user_id'  %>
<%= hidden_field 'post', 'updated_user_id'  %>
 <%= submit_tag 'Edit', class:"btn btn-info" %>
<input type="reset" class="btn btn-secondary" name="Clear" value="Clear">
<% end -%><br>
<%= link_to 'Back', {:action => 'list'} %>
</div>

app/views/posts/index.html.erb
<h1>Post index

app/views/posts/list.html.erb
<h3>Post List</h3>
<div style="float:right">
<%= form_tag :action => 'search' do %>
  <label>Keyword :</label>
  <%= text_field_tag :search, params[:search], placeholder: "Enter title or description" %>
  <%= submit_tag "Search", class:'btn btn-primary' %>
  <%= link_to 'Create', posts_new_path, class:"btn btn-info" %>
  <%= link_to 'Upload', posts_upload_path, class:"btn btn-warning"%>
  <%= link_to 'Download', posts_export_path(format: "xls"), class:"btn btn-success"%>
  </div>
<br/><br>
<table class="table table-hover table-bordered">
  <tr class="table-info">
  <th>Post Title</th>
  <th>Post Description</th>
  <th>Posted User</th>
  <th>Posted Date</th>
  <th>Operation</th>
  </tr>
  <% @posts.each do |post| %>
  <tr>
  <td><%= link_to post.title, {:action => "show", :id => post.id} %></td>
  <td><%= post.description %></td>
  <td><%= post.create_user_id%></td>
  <td><%= post.created_at.strftime("%Y/%m/%d") %></td>
  <td>
  <%= link_to 'Edit', {:action => "edit", :id => post.id}, class:"btn btn-success" %>
  <%= link_to 'Delete', {:action => 'delete', :id => post.id}, data:{confirm: "Are you sure to delete?" }, class:"btn btn-danger" %>
  </td>
  </tr>
  <% end %>
  <% end %>
</table>
<div style="text-align:right">
<%= will_paginate @posts, renderer: BootstrapPagination::Rails  %>
</div>

app/views/posts/new.html.erb
<% if @post.errors.any? %>
<ul>
<% @post.errors.full_messages.each do |msg| %>
<li><%= msg %>
<% end %>
</ul>
<% end %>
<div class="container">
<h3>Create Post</h3><br>
<%= form_for @post, :url =>{:action => "confirm"} do %>
<div class="form-group">
<label for = "post_title">Title:</label><br>
<%= text_field 'post', 'title' , class:'form-control' %>
</div><br>
<div class="form-group">
<label for = "post_description">Description:</label><br/>
<%= text_area 'post', 'description' , class:'form-control' %>
</div>
<br>
<%= submit_tag "Create", class:'btn btn-primary' %>
<input type="reset" class="btn btn-secondary" name="Clear" value="Clear">
<% end -%><br>
<%= link_to 'Back', {:action => 'list'} %>
</div>

app/views/posts/showDetail.html.erb
<h3>Post Details</h3><br>
<div class="container">
<div class="row">
<div class="col-sm-2">
<label>Title</label><br><br>
<label>Description</label><br><br>
<label>Status</label><br><br>
<label>Created Date</label><br><br>
<label>Created User ID</label><br><br>
<label>Updated Date</label><br><br>
<label>Updated User ID</label><br>
</div>
<div class="col-sm-10">
<%= @post.title %><br><br>
<%= @post.description %><br><br>
<% if @post.status == '0' %>
  <%= @post.status = 'Inactive' %><br><br>
<% else %>
  <%= @post.status = 'Active' %><br><br>
<% end %>
<%= @post.created_at.strftime("%Y/%m/%d") %><br><br>
<%= @post.create_user_id %><br><br>
<%= @post.updated_at.strftime("%Y/%m/%d") %><br><br>
<%= @post.updated_user_id %>
</div>
</div><br>
<%= link_to 'Back', {:action => 'list'} %>

app/views/posts/upload.html.erb
<div class="container-fluid">
<h3>Upload CSV File</h3><br>
<%= form_tag :action => 'import', multipart: true do %>
<label for = "csv_file">CSV file:</label>
  <%= file_field_tag :file %><br><br>
  <%= submit_tag "Upload", class:'btn btn-primary' %>
<input type="reset" class="btn btn-secondary" name="Clear" value="Clear">
<% end %>
  </div>

app/views/users/confirmUser.html.erb
<% if @user.errors.any? %>
<h2>The following errors prevented user from getting created.</h2>
<ul>
<% @user.errors.full_messages.each do |msg| %>
<li><%= msg %>
<% end %>
</ul>
<% end %>
<h2>Register Confirm</h2>
<div class="container">
<%= form_for @user, :url =>{:action => "create"}, multipart: true do %>
<div class="mb-3 row">
    <label for = "user_name" class="col-sm-2 col-form-label">Name</label>
    <div class="col-sm-10">
    <%= text_field 'user', 'name' , class:'form-control' %>
    </div>
    </div>
<div class="mb-3 row">
    <label for = "user_email" class="col-sm-2 col-form-label">E-mail address</label>
    <div class="col-sm-10">
    <%= text_area 'user', 'email' , class:'form-control' %>
    </div>
    </div>
    <div class="mb-3 row">
     <label for = "user_password" class="col-sm-2 col-form-label">Password</label>
    <div class="col-sm-10">
    <%= password_field 'user', 'password' , class:'form-control' %>
    </div>
    </div>
    <div class="mb-3 row">
    <label for = "user_password" class="col-sm-2 col-form-label">Confirm Password</label>
    <div class="col-sm-10">
    <%= password_field 'user', 'password' , class:'form-control' %>
    </div>
    </div>
    <div class="mb-3 row">
    <label for = "user_type" class="col-sm-2 col-form-label">Type</label>
    <div class="col-sm-10">
    <%= text_field 'user', 'user_type', class:'form-control' %>
    </select>
    </div>
    </div>
    <div class="mb-3 row">
    <label for = "user_phone" class="col-sm-2 col-form-label">Phone</label>
    <div class="col-sm-10">
    <%= text_field 'user', 'phone' , class:'form-control' %>
    </div>
    </div>
    <div class="mb-3 row">
     <label for = "user_dob" class="col-sm-2 col-form-label">Date of Birth</label>
    <div class="col-sm-10">
    <%= text_field 'user', 'dob', class:'form-control', type: "date",
        data: {
      controller: "flatpickr",
      flatpickr_date_format: "Y-m-d",
      flatpickr_min_date: Time.zone.now
    } %>
    </div>
    </div>
    <div class="mb-3 row">
     <label for = "user_address" class="col-sm-2 col-form-label">Address</label>
    <div class="col-sm-10">
    <%= text_area 'user', 'address' , class:'form-control' %>
    </div>
    </div>
    <div class="mb-3 row">
     <label for = "user_profile" class="col-sm-2 col-form-label">Profile</label>
    <div class="col-sm-10">
    <%= text_field 'user', 'profile', class:'form-control'%>
    </div>
    </div>
    <div class="mb-3 row">
    <label for = "blank" class="col-sm-2 col-form-label"></label>
    <div class="col-sm-10">
    <%= submit_tag "Confirm", class:'btn btn-primary' %>
    <input type="reset" class="btn btn-secondary" name="Clear" value="Clear">
    </div>
    </div>
    <% end -%><br>
    </div>
    </div>

app/views/users/editProfile.html.erb
<h3>Profile Edit</h3><br>
<div class="container">
<%= form_for @user, :url =>{:action => "update", :id => session[:user_id]} do %>
 <label for = "user_name">Name:</label>
 <%= text_field 'user', 'name' , class:'form-control' %>
    <label for = "user_email">E-mail address:</label>
    <%= text_field 'user', 'email' , class:'form-control' %>
    <label for = "user_type">Type:</label>
    <%= text_field 'user', 'user_type' , class:'form-control' %>
    <label for = "user_phone">Phone:</label>
    <%= text_field 'user', 'phone' , class:'form-control' %>
    <label for = "user_dob">Date of Birth:</label>
    <%= text_field 'user', 'dob' , class:'form-control', type: "date",
      data: {
      controller: "flatpickr",
      flatpickr_date_format: "Y-m-d",
      flatpickr_min_date: Time.zone.now
    }
     %>
    <label for = "user_address">Address:</label>
    <%= text_area 'user', 'address' , class:'form-control' %>
    <label for = "user_profile">New Profile:</label>
    <%= text_area 'user', 'profile' , class:'form-control' %><br>
    <%= submit_tag 'Edit', class:"btn btn-info" %>
    <input type="reset" class="btn btn-secondary" name="Clear" value="Clear">
    <%= link_to 'Change Password' , auths_changePsw_path %>
    <% end %>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/list.html.erb
<h3>User List</h3>
<%= form_tag :action => 'search' do %>
<div class="row g-3" style="float:right">
  <div class="col-auto">
  <label class="col-form-label">Name:</label>
  </div>
  <div class="col-auto">
  <%= text_field_tag :name, params[:name] , class:'form-control' %>
  </div>
  <div class="col-auto">
  <label class="col-form-label">Email:</label>
  </div>
  <div class="col-auto">
  <%= text_field_tag :email, params[:email] , class:'form-control' %>
  </div>
  <div class="col-auto">
  <label class="col-form-label">From:</label>
  </div>
  <div class="col-auto">
  <%= text_field_tag :from_date, params[:from_date], class:'form-control', type: "date",
        data: {
      controller: "flatpickr",
      flatpickr_date_format: "Y-m-d",
      flatpickr_min_date: Time.zone.now
    }
   %>
  </div>
  <div class="col-auto">
  <label class="col-form-label">To:</label>
  </div>
  <div class="col-auto">
  <%= text_field_tag :to_date, params[:to_date] , class:'form-control', type: "date",
        data: {
      controller: "flatpickr",
      flatpickr_date_format: "Y-m-d",
      flatpickr_min_date: Time.zone.now
    }
   %>
  </div>
  <div class="col-auto">
  <%= submit_tag 'Search', class:"btn btn-info" %>
  </div>
</div><br><br>
<table class="table table-hover table-bordered">
  <tr class="table-info">
  <th>ID</th>
  <th>Name</th>
  <th>Email</th>
  <th>Created User</th>
  <th>Type</th>
  <th>Phone</th>
  <th>Date of Birth</th>
  <th>Address</th>
  <th>Created Date</th>
  <th>Updated Date</th>
  <th>Operation</th>
  </tr>
  <% @users.each do |user| %>
  <tr>
  <td><%= user.id %></td>
  <td><%= user.name %></td>
  <td><%= user.email %></td>
  <td><%= user.name %></td>
  <td>
  <% if user.user_type == '0' %>
    <%= user.user_type = 'Admin' %>
  <% else %>
    <%= user.user_type = 'User' %>
  <% end %>
  </td>
  <td><%= user.phone %></td>
  <td><%= user.dob %></td>
  <td><%= user.address %></td>
  <td><%= user.created_at.strftime("%Y/%m/%d") %></td>
  <td><%= user.updated_at.strftime("%Y/%m/%d") %></td>
  <td>
   <%= link_to 'Delete', {:action => "delete", :id => user.id, data:{confirm: "Are you sure to delete?" }  }, class:"btn btn-danger" %>
  </td>
  </tr>
  <% end %>
</table>
<% end %>
<div style="text-align:right">
<%= will_paginate @users, renderer: BootstrapPagination::Rails  %>
</div>

app/views/users/profile.html.erb
<h3>Profile</h3><br>
<div class="container">
  <div class="row">
    <div class="col-sm-2">
   <%= @user.profile %>
    </div>
    <div class="col-sm-2">
      <label for = "user_name">Name</label><br><br>
      <label for = "user_type">Type</label><br><br>
      <label for = "user_email">Email</label><br><br>
      <label for = "user_phone">Phone</label><br><br>
      <label for = "user_dob">Date of Birth</label><br><br>
      <label for = "user_address">Address</label><br><br>
      <%= link_to 'Edit Profile', {:action => "editProfile", :id => session[:user_id]}, class:"btn btn-primary" %>
    </div>
    <div class="col-sm-8">
      <%= @user.name %><br><br>
      <% if @user.user_type == '0' %>
      <%= @user.user_type = 'Admin' %>
      <% else %>
      <%= @user.user_type = 'User' %>
      <% end %><br><br>
      <%= @user.email %><br><br>
      <%= @user.phone %><br><br>
      <%= @user.dob %><br><br>   
      <%= @user.address %>
    </div>
  </div>
</div>